### ISSUE TITLE
Get CLI working

### ISSUE THREAD

**Issue by cholmes** [opengeos/open-buildings#2]
### Environment Information

-   open_buildings version: 0.2
-   Python version: 3.10?
-   Operating System: Mac OS

### Description

Trying to use the CLI for open buildings. It seems like something is sorta there - it installs open_buildings on the path (which is further than I got on my own), but then it says to replace this message by 'putting your code in open_buildings.cli.main'.

It seems like it'd be nice to align the `pip install open-buildings` with the cli, like have both be `open-buildings` or both be `open_buildings`.

Originally reported in https://github.com/cholmes/google-buildings-tools/issues/1

### What I Did

```
% open-buildings
zsh: command not found: open-buildings
% open_buildings
Replace this message by putting your code into open_buildings.cli.main
See click documentation at https://click.palletsprojects.com/
```

**Comment by giswqs** [comment]
I am working on it now.

**Comment by cholmes** [comment]
So I built up the click interface in the open_buildings.py, see https://github.com/opengeos/open-buildings/blob/a82f12991864fe1eccc5cb255f741e112323684f/open_buildings/open_buildings.py#L472 and https://github.com/opengeos/open-buildings/blob/a82f12991864fe1eccc5cb255f741e112323684f/open_buildings/open_buildings.py#L512

So do we just need to move the click definitions ones to the cli.py?

**Comment by cholmes** [comment]
The 'usage' stuff in https://github.com/opengeos/open-buildings#functionality was generated by the CLI I had - and I managed to get it so I could use the CLI, but failed to get it so it would install right. Your new package definitely installs it right - just not sure how to hook it up.

**Comment by giswqs** [comment]
Correct. Just move the cli interface from the main module to cli.py. It should work. The entry point is in `setup.py`. 

https://github.com/opengeos/open-buildings/blob/main/setup.py#L44
```python
    entry_points={
        'console_scripts': [
            'open_buildings=open_buildings.cli:main',
        ],
    },
```

I think the problem with your previous repo was that the command in the entry_points has hyphens rather than undersores. Commands should have not hyphens. 

https://github.com/cholmes/google-buildings-tools/blob/main/setup.py#L10
```python
    entry_points={
        'console_scripts': [
            'google-buildings-cli=google_buildings_cli:main',
        ],
    },
```

**Comment by giswqs** [comment]
I just added you as the owner of the package on PyPI. Check your email.

**Comment by cholmes** [comment]
> It is automatically pushed to pypi once a release is created.

> https://pypi.org/project/open-buildings/

Oh cool! I tried once but failed to update the versions, then forgot to check on the one after I did it right. Thanks!

**Comment by cholmes** [comment]
Ah darn, I thought I had the CLI working, as it was returning responses, but I think I didn't actually hook it up right:

```
Traceback (most recent call last):
  File "/Users/cholmes/repos/venv/gob/bin/open_buildings", line 33, in <module>
    sys.exit(load_entry_point('open-buildings==0.0.4', 'console_scripts', 'open_buildings')())
  File "/Users/cholmes/repos/venv/gob/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cholmes/repos/venv/gob/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/cholmes/repos/venv/gob/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cholmes/repos/venv/gob/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cholmes/repos/venv/gob/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/cholmes/repos/venv/gob/lib/python3.9/site-packages/open_buildings/cli.py", line 54, in benchmark
    results = process_benchmark(
NameError: name 'process_benchmark' is not defined
```

How do I get two python files to work with one another? Like how do I properly call the definitions in https://github.com/opengeos/open-buildings/blob/main/open_buildings/open_buildings.py from the cli (https://github.com/opengeos/open-buildings/blob/main/open_buildings/cli.py) - I moved the definitions, but was hoping since they were in the same directory it'd work.

**Comment by cholmes** [comment]
Ok, think I figured this out, just need the import statements. Going to close this in the hope that the CLI is truly working in 0.5. Would be great if someone could confirm that to be true...
